spring:
  mail:
    username: onthemountain89@gmail.com
    password: bmdvxjeclvujlmgb
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
server:
  port: 8081